language: python

python:
  - 2.7
  - 3.3
  - 3.4

env:
  - DJANGO=Django==1.4
  - DJANGO=Django==1.5
  - DJANGO=Django==1.6
  - DJANGO="git+git://github.com/django/django.git@master#egg=django"

install:
  - pip install -q $DJANGO

script:
  - python setup.py test

matrix:
  exclude:
    - python: 3.3
      env: DJANGO=Django==1.4
    - python: 3.4
      env: DJANGO=Django==1.4
  allow_failures:
      - env: DJANGO="git+git://github.com/django/django.git@master#egg=django"
